---

- hosts: all
  become: true
  user: root

  vars:
    packages:
      - vim
      - tmux
      - python
      - php5
      - php5-gd
      - php5-curl
      - php5-imagick
      - php5-mysql
    #  - php5-mysqli
      - php5-mcrypt
      - phpunit
      - apache2
      - libapache2-mod-php5
      - nodejs
      - npm
    MySQL_root_pass: MySQL_P@ssw0rd
  
  tasks:
    - name: set timezone to bangkok
      timezone: name="Asia/Bangkok"
      tags: server

    - name: install packages
      package:
        name: "{{item}}"
        state: "latest"
      with_items: "{{packages}}"
      tags: server

    - name: create symlink /usr/bin/node --> /usr/bin/nodejs
      file:
        state: link
        path: /usr/bin/node
        src: /usr/bin/nodejs
      tags: server

    - name: create 10 groups
      group: 
        name: "{{item}}"
      with_sequence: start=1 end=10 format="team%d"
      tags: server

    - name: add 10 users
      user:
        name: "{{item}}"
        createhome: yes
        groups: "{{item}}"
        password: "{{ ('Password'+item) | password_hash('sha512') }}"
        update_password: always #on_create
        state: present
      with_sequence: start=1 end=10 format="team%d"
      tags: server

    - name: set www-data to all the groups
      user:
        name: "www-data"
        append: yes
        group: "www-data"
        groups: "{{item}}"
      with_sequence: start=1 end=10 format="team%d"
      tags: server

    - name: create html folder for each user
      file:
        state: directory
        path: "/var/www/{{item}}"
        owner: "{{item}}"
        group: "{{item}}"
        mode: 0770
        recurse: yes
      with_sequence: start=1 end=10 format="team%d"
      tags: server

    - name: create symlink to the folder inside home of each user
      file:
        state: link
        path: "/home/{{item}}/html"
        src: "/var/www/{{item}}"
        owner: "{{item}}"
        group: "{{item}}"
        mode: 0770
      with_sequence: start=1 end=10 format="team%d"
      tags: server

    - name: copy apache config for all teams
      template:
        src: "apache-site.conf.j2"
        dest: "/etc/apache2/sites-available/team{{item}}.conf"
        owner: root
        group: root
        mode: 0644
      with_sequence: start=1 end=10
      tags: apache

    - name: enable mod
      apache2_module:
        name: "{{item}}"
        state: present
      with_items:
        - rewrite
        - headers
        - php5
      notify:
        - restart apache2
      tags: apache

    - name: enable sites
      command: a2ensite team*
      notify:
        - restart apache2
      tags: apache

    - name: set default page for global
      copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
      tags: apache, files

    - name: set default page for each team
      template:
        src: team_index.html.j2
        dest: /var/www/{{ item }}/index.html
        owner: root
        group: root
        mode: 0644
      with_sequence: start=1 end=10 format="team%d"
      tags: apache, files

    - name: install php composer
      get_url:
        url: https://getcomposer.org/composer.phar
        dest: /usr/local/bin/composer
        mode: 0755
      tags: dev, server

    - name: install bower
      command: npm install -g bower
      tags: dev, server

    # ----------- setup MySQL -----------
    - name: Set MySQL root password before installing
      debconf: name='mysql-server' question='mysql-server/root_password' value='{{MySQL_root_pass | quote}}' vtype='password'
      when: ansible_os_family == "Debian"
      tags: mysql

    - name: Confirm MySQL root password before installing
      debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{MySQL_root_pass | quote}}' vtype='password'
      when: ansible_os_family == "Debian"
      tags: mysql

    - name: Install MySQL
      apt: package={{ item }} state=installed force=yes update_cache=yes cache_valid_time=3600
      when: ansible_os_family == "Debian"
      with_items:
        - mysql-server
        - mysql-client
        - python-mysqldb
      notify:
        - restart mysql
      tags: mysql

    - name: Deletes anonymous MySQL server user for localhost
      mysql_user: user="" state="absent" login_password="{{ MySQL_root_pass }}" login_user="root"
      tags: mysql

    - name: Secures the MySQL root user
      mysql_user: user="root" password="{{ MySQL_root_pass }}" host="{{ item }}" login_password="{{MySQL_root_pass}}" login_user="root"
      with_items:
        - 127.0.0.1
        - localhost
        - ::1
      # - "{{ ansible_fqdn }}"
      notify:
        - restart mysql
      tags: mysql

    - name: Removes the MySQL test database
      mysql_db: db=test state=absent login_password="{{ MySQL_root_pass }}" login_user="root"
      tags: mysql

    - name: create MySQL database for each team
      mysql_db: db="{{ item }}" state=present login_password="{{ MySQL_root_pass }}" login_user="root"
      with_sequence: start=1 end=10 format="team%d"
      tags: mysql

    - name: create MySQL account for each team
      mysql_user: user="{{ item }}" password="password" host="localhost" priv="{{item}}.*:ALL" login_password="{{MySQL_root_pass}}" login_user="root"
      with_sequence: start=1 end=10 format="team%d"
      tags: mysql

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted

    - name: restart mysql
      service: name=mysql state=restarted

