---

- hosts: all
  become: true
  user: vagrant

  vars:
    packages:
      - vim
      - tmux
      - python
      - php5
      - php5-gd
      - php5-curl
      - php5-imagick
      - php5-mysql
      - php5-mcrypt
      - phpunit
      - apache2
      - libapache2-mod-php5
#      - php5.6
#      - php5.6-mbstring
#      - php5.6-mcrypt
#      - php5.6-mysql
#      - php5.6-xml
  
  tasks:
    - name: set timezone to bangkok
      timezone: name="Asia/Bangkok"

#    - name: add php5.6 apt repo
#      apt_repository:
#        name: "ppa:ondrej/php"
#        status: present

    - name: install packages
      package:
        name: "{{item}}"
        state: "latest"
      with_items: "{{packages}}"

    - name: create 10 groups
      group: 
        name: "{{item}}"
      with_sequence: start=1 end=10 format="team%d"

    - name: add 10 users
      user:
        name: "{{item}}"
        createhome: yes
        groups: "{{item}}"
        password: "{{ item | password_hash('sha512') }}"
        state: "present"
      with_sequence: start=1 end=10 format="team%d"

    - name: set www-data to all the groups
      user:
        name: "www-data"
        append: yes
        group: "www-data"
        groups: "{{item}}"
      with_sequence: start=1 end=10 format="team%d"


# a2enmod php5.6
