USE team1;

/*--------- book data -----------*/
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id INTEGER(4) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(256) NOT NULL,
    password VARCHAR(256) NOT NULL
);

INSERT INTO users(username, password) VALUES 
('admin', 'Pass@1234'),
('alice', '1234'),
('bob', '1234');

/*--------- book data -----------*/
DROP TABLE IF EXISTS books;

CREATE TABLE books (
    id INTEGER(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(256) NOT NULL,
    author VARCHAR(256) NOT NULL
);

INSERT INTO books(title, author) VALUES
("The Hunger Games (The Hunger Games, #1)", "Suzanne Collins"),
("Harry Potter and the Order of the Phoenix (Harry Potter, #5)", "J.K.  Rowling"),
("To Kill a Mockingbird", "Harper Lee"),
("Pride and Prejudice", "Jane Austen"),
("Twilight (Twilight, #1)", "Stephenie Meyer"),
("The Chronicles of Narnia (Chronicles of Narnia, #1-7)", "C.S. Lewis"),
("The Book Thief", "Markus Zusak"),
("Animal Farm", "George Orwell"),
("Gone with the Wind", "Margaret Mitchell"),
("The Hitchhiker's Guide to the Galaxy (Hitchhiker's Guide to the Galaxy, #1)", "Douglas Adams"),
("The Giving Tree", "Shel Silverstein"),
("The Fault in Our Stars", "John Green"),
("J.R.R. Tolkien 4-Book Boxed Set: The Hobbit and The Lord of the Rings", "J.R.R. Tolkien"),
("Wuthering Heights", "Emily Brontë"),
("The Da Vinci Code (Robert Langdon, #2)", "Dan Brown"),
("Memoirs of a Geisha", "Arthur Golden"),
("Alice's Adventures in Wonderland &amp; Through the Looking-Glass", "Lewis Carroll"),
("Les Misérables", "Victor Hugo"),
("Divergent (Divergent, #1)", "Veronica Roth"),
("Romeo and Juliet", "William Shakespeare"),
("The Picture of Dorian Gray", "Oscar Wilde"),
("Lord of the Flies", "William Golding"),
("Jane Eyre", "Charlotte Brontë"),
("The Alchemist", "Paulo Coelho"),
("Ender's Game (Ender's Saga, #1)", "Orson Scott Card"),
("Crime and Punishment", "Fyodor Dostoyevsky"),
("The Time Traveler's Wife", "Audrey Niffenegger"),
("City of Bones (The Mortal Instruments, #1)", "Cassandra Clare"),
("Charlotte's Web", "E.B. White"),
("The Help", "Kathryn Stockett"),
("The Perks of Being A Wallflower", "Stephen Chbosky"),
("Anne of Green Gables (Anne of Green Gables, #1)", "L.M. Montgomery"),
("Of Mice and Men", "John Steinbeck"),
("The Great Gatsby", "F. Scott Fitzgerald"),
("Dracula", "Bram Stoker"),
("Brave New World", "Aldous Huxley"),
("One Hundred Years of Solitude", "Gabriel García Márquez"),
("The Princess Bride", "William Goldman"),
("A Wrinkle in Time (A Wrinkle in Time Quintet, #1)", "Madeleine L&#39;Engle"),
("The Secret Garden", "Frances Hodgson Burnett"),
("A Thousand Splendid Suns", "Khaled Hosseini"),
("The Catcher in the Rye", "J.D. Salinger"),
("The Little Prince", "Antoine de Saint-Exupéry (Author/Illustrator)"),
("The Adventures of Huckleberry Finn", "Mark Twain"),
("The Lovely Bones", "Alice Sebold"),
("Where the Wild Things Are", "Maurice Sendak"),
("Green Eggs and Ham", "Dr. Seuss"),
("Fahrenheit 451", "Ray Bradbury"),
("Water for Elephants", "Sara Gruen"),
("Life of Pi", "Yann Martel"),
("A Tale of Two Cities", "Charles Dickens"),
("The Odyssey", "Homer"),
("A Game of Thrones (A Song of Ice and Fire, #1)", "George R.R. Martin"),
("The Lightning Thief (Percy Jackson and the Olympians, #1)", "Rick Riordan"),
("The Outsiders", "S.E. Hinton"),
("Lolita", "Vladimir Nabokov"),
("Slaughterhouse-Five", "Kurt Vonnegut"),
("Catch-22", "Joseph Heller"),
("Dune", "Frank Herbert"),
("The Pillars of the Earth (The Pillars of the Earth, #1)", "Ken Follett"),
("Frankenstein", "Mary Shelley"),
("The Stand", "Stephen King"),
("Watership Down (Watership Down #1)", "Richard Adams"),
("The Kite Runner", "Khaled Hosseini"),
("The Adventures of Sherlock Holmes (Sherlock Holmes, #3)", "Arthur Conan Doyle"),
("My Sister's Keeper", "Jodi Picoult"),
("The Giver (The Giver, #1)", "Lois Lowry"),
("One Flew Over the Cuckoo's Nest", "Ken Kesey"),
("The Bell Jar", "Sylvia Plath"),
("The Handmaid's Tale", "Margaret Atwood"),
("Outlander (Outlander #1)", "Diana Gabaldon"),
("Anna Karenina", "Leo Tolstoy"),
("A Tree Grows in Brooklyn", "Betty  Smith"),
("Rebecca", "Daphne du Maurier"),
("Harry Potter and the Sorcerer's Stone (Harry Potter, #1)", "J.K. Rowling"),
("The Color Purple", "Alice Walker"),
("The Girl with the Dragon Tattoo (Millennium, #1)", "Stieg Larsson"),
("Angela's Ashes (Frank McCourt, #1)", "Frank McCourt"),
("The Road", "Cormac McCarthy"),
("A Clockwork Orange", "Anthony Burgess"),
("Matilda", "Roald Dahl"),
("Little Women (Little Women, #1)", "Louisa May Alcott"),
("The Brothers Karamazov", "Fyodor Dostoyevsky"),
("Vampire Academy (Vampire Academy, #1)", "Richelle Mead"),
("The Poisonwood Bible", "Barbara Kingsolver"),
("The Fellowship of the Ring (The Lord of the Rings, #1)", "J.R.R. Tolkien"),
("Siddhartha", "Hermann Hesse"),
("Atlas Shrugged", "Ayn Rand"),
("Don Quixote", "Miguel de Cervantes Saavedra"),
("Fahrenheit 451", "Ray Bradbury"),
("The Golden Compass (His Dark Materials, #1)", "Philip Pullman"),
("The Notebook (The Notebook, #1)", "Nicholas Sparks"),
("The Old Man and the Sea", "Ernest Hemingway"),
("Great Expectations", "Charles Dickens"),
("A Prayer for Owen Meany", "John Irving"),
("The Complete Stories and Poems", "Edgar Allan Poe"),
("Moby-Dick; or, The Whale", "Herman Melville"),
("Interview with the Vampire (The Vampire Chronicles, #1)", "Anne Rice"),
("Winnie-the-Pooh (Winnie-the-Pooh, #1)", "A.A. Milne"),
("The Red Tent", "Anita Diamant"),
("The Secret Life of Bees", "Sue Monk Kidd"),
("Harry Potter and the Deathly Hallows (Harry Potter, #7)", "J.K. Rowling"),
("Clockwork Angel (The Infernal Devices, #1)", "Cassandra Clare"),
("Middlesex", "Jeffrey Eugenides"),
("Great Expectations", "Charles Dickens"),
("The Adventures of Tom Sawyer", "Mark Twain"),
("On the Road", "Jack Kerouac"),
("The Stranger", "Albert Camus"),
("Charlie and the Chocolate Factory (Charlie Bucket, #1)", "Roald Dahl"),
("The Master and Margarita", "Mikhail Bulgakov"),
("1984", "George Orwell"),
("Eragon (The Inheritance Cycle, #1)", "Christopher Paolini"),
("The Very Hungry Caterpillar", "Eric Carle"),
("Tuesdays with Morrie", "Mitch Albom"),
("The Shining (The Shining #1)", "Stephen King"),
("And Then There Were None", "Agatha Christie"),
("The Unbearable Lightness of Being", "Milan Kundera"),
("The Shadow of the Wind (The Cemetery of Forgotten Books,  #1)", "Carlos Ruiz Zafón"),
("The Curious Incident of the Dog in the Night-Time", "Mark Haddon"),
("The Scarlet Letter", "Nathaniel Hawthorne"),
("Flowers for Algernon", "Daniel Keyes"),
("Looking for Alaska", "John Green"),
("Hush, Hush (Hush, Hush, #1)", "Becca Fitzpatrick"),
("The Metamorphosis", "Franz Kafka"),
("The Name of the Rose", "Umberto Eco"),
("The Five People You Meet in Heaven", "Mitch Albom"),
("Harry Potter and the Prisoner of Azkaban (Harry Potter, #3)", "J.K.  Rowling"),
("The Godfather", "Mario Puzo"),
("The Name of the Wind (The Kingkiller Chronicle, #1)", "Patrick Rothfuss"),
("Lonesome Dove", "Larry McMurtry"),
("In Cold Blood", "Truman Capote"),
("The Cat in the Hat", "Dr. Seuss"),
("The Compleat Works of Wllm Shkspr", "Reduced Shakespeare Company"),
("The Little House Collection (Little House, #1-9)", "Laura Ingalls Wilder"),
("Fight Club", "Chuck Palahniuk"),
("Watchmen", "Alan Moore"),
("The Divine Comedy", "Dante Alighieri"),
("Holes (Holes, #1)", "Louis Sachar"),
("Shadow Kiss (Vampire Academy, #3)", "Richelle Mead"),
("All Quiet on the Western Front", "Erich Maria Remarque"),
("Peter Pan", "J.M. Barrie"),
("American Gods (American Gods, #1)", "Neil Gaiman"),
("Insurgent (Divergent, #2)", "Veronica Roth"),
("A Walk to Remember", "Nicholas Sparks"),
("Perfume: The Story of a Murderer", "Patrick Süskind"),
("Harry Potter and the Goblet of Fire (Harry Potter, #4)", "J.K. Rowling"),
("Love in the Time of Cholera", "Gabriel García Márquez"),
("The Thorn Birds", "Colleen McCullough"),
("The Last Olympian (Percy Jackson and the Olympians, #5)", "Rick Riordan"),
("The Lion, the Witch, and the Wardrobe (Chronicles of Narnia, #1)", "C.S.  Lewis"),
("It", "Stephen King"),
("Their Eyes Were Watching God", "Zora Neale Hurston"),
("Frostbite (Vampire Academy, #2)", "Richelle Mead"),
("How the Grinch Stole Christmas!", "Dr. Seuss"),
("Eat, Pray, Love", "Elizabeth Gilbert"),
("Atonement", "Ian McEwan"),
("The Ultimate Hitchhiker's Guide to the Galaxy (Hitchhiker's Guide to the),
(Galaxy #1-5)", "Douglas Adams"),
("Goodnight Moon", "Margaret Wise Brown"),
("The Importance of Being Earnest", "Oscar Wilde"),
("Harry Potter and the Half-Blood Prince (Harry Potter, #6)", "J.K. Rowling"),
("The Wonderful Wizard of Oz (Oz, #1)", "L. Frank Baum"),
("Blood Promise (Vampire Academy, #4)", "Richelle Mead"),
("The Three Musketeers", "Alexandre Dumas"),
("The Lorax", "Dr. Seuss"),
("The Good Earth (House of Earth, #1)", "Pearl S. Buck"),
("The Count of Monte Cristo", "Alexandre Dumas"),
("Where the Red Fern Grows", "Wilson Rawls"),
("Tess of the D'Urbervilles", "Thomas Hardy"),
("A Midsummer Night's Dream", "William Shakespeare"),
("The Mists of Avalon (Avalon, #1)", "Marion Zimmer Bradley"),
("The Prophet", "Kahlil Gibran"),
("Heart of Darkness", "Joseph Conrad"),
("The Joy Luck Club", "Amy Tan"),
("Jonathan Livingston Seagull", "Richard Bach"),
("Good Omens: The Nice and Accurate Prophecies of Agnes Nutter, Witch", "Terry Pratchett"),
("The Battle of the Labyrinth (Percy Jackson and the Olympians, #4)", "Rick Riordan"),
("The Phantom Tollbooth", "Norton Juster"),
("Madame Bovary", "Gustave Flaubert"),
("Alice in Wonderland (Alice's Adventures in Wonderland, #1)", "Lewis Carroll"),
("The Call of the Wild", "Jack London"),
("Fifty Shades of Grey (Fifty Shades, #1)", "E.L. James"),
("The Girl Who Played with Fire (Millennium, #2)", "Stieg Larsson"),
("The Sea of Monsters (Percy Jackson and the Olympians, #2)", "Rick Riordan"),
("Bridge to Terabithia", "Katherine Paterson"),
("Oh, The Places You'll Go!", "Dr. Seuss"),
("Oliver Twist", "Charles Dickens"),
("The Canterbury Tales", "Geoffrey Chaucer"),
("The Titan's Curse (Percy Jackson and the Olympians, #3)", "Rick Riordan"),
("The Clan of the Cave Bear (Earth's Children, #1)", "Jean M. Auel"),
("Ulysses", "James Joyce"),
("The Hunger Games Trilogy Boxset (The Hunger Games, #1-3)", "Suzanne Collins"),
("Harry Potter and the Chamber of Secrets (Harry Potter, #2)", "J.K.  Rowling"),
("Clockwork Princess (The Infernal Devices, #3)", "Cassandra Clare"),
("A Farewell to Arms", "Ernest Hemingway"),
("The World According to Garp", "John Irving"),
("The Maze Runner (Maze Runner, #1)", "James Dashner"),
("Wicked: The Life and Times of the Wicked Witch of the West (The Wicked Years,),
(#1)", "Gregory Maguire"),
("Treasure Island", "Robert Louis Stevenson"),
("The Neverending Story", "Michael Ende"),
("The Other Boleyn Girl (The Plantagenet and Tudor Novels, #9)", "Philippa Gregory"),
("David Copperfield", "Charles Dickens"),
("Last Sacrifice (Vampire Academy, #6)", "Richelle Mead"),
("Fallen (Fallen, #1)", "Lauren Kate"),
("Thirteen Reasons Why", "Jay Asher"),
("Extremely Loud and Incredibly Close", "Jonathan Safran Foer"),
("Shōgun (Asian Saga, #1)", "James Clavell"),
("A Storm of Swords (A Song of Ice and Fire, #3)", "George R.R. Martin"),
("Schindler's List", "Thomas Keneally"),
("His Dark Materials (His Dark Materials #1-3)", "Philip Pullman"),
("Spirit Bound (Vampire Academy, #5)", "Richelle Mead"),
("A Little Princess", "Frances Hodgson Burnett"),
("The Sun Also Rises", "Ernest Hemingway"),
("A Confederacy of Dunces", "John Kennedy Toole"),
("The Secret Magdalene", "Ki Longfellow"),
("Beloved (The Trilogy, #1)", "Toni Morrison"),
("The Velveteen Rabbit", "Margery Williams Bianco"),
("Shiver (The Wolves of Mercy Falls, #1)", "Maggie Stiefvater"),
("The Crucible", "Arthur Miller"),
("She's Come Undone", "Wally Lamb"),
("Girl with a Pearl Earring", "Tracy Chevalier"),
("Jurassic Park", "Michael Crichton"),
("Cat's Cradle", "Kurt Vonnegut"),
("The Silmarillion", "J.R.R. Tolkien"),
("The Boy in the Striped Pajamas", "John Boyne"),
("The Hobbit", "J.R.R. Tolkien"),
("The Hiding Place: The Triumphant True Story of Corrie Ten Boom", "Corrie ten Boom"),
("The Wind in the Willows", "Kenneth Grahame"),
("Marley and Me: Life and Love With the World's Worst Dog", "John Grogan"),
("A Light in the Attic", "Shel Silverstein"),
("Uglies (Uglies, #1)", "Scott Westerfeld"),
("The God of Small Things", "Arundhati Roy"),
("Murder on the Orient Express (Hercule Poirot, #10)", "Agatha Christie"),
("Clockwork Prince (The Infernal Devices, #2)", "Cassandra Clare"),
("City of Fallen Angels (The Mortal Instruments, #4)", "Cassandra Clare"),
("Marked (House of Night, #1)", "P.C. Cast"),
("The Lost Hero (The Heroes of Olympus, #1)", "Rick Riordan"),
("The Silence of the Lambs  (Hannibal Lecter, #2)", "Thomas Harris"),
("The Screwtape Letters", "C.S. Lewis"),
("The Iliad/The Odyssey", "Homer"),
("The Trial", "Franz Kafka"),
("Midnight Sun (Twilight, #1.5)", "Stephenie Meyer"),
("Ella Enchanted", "Gail Carson Levine"),
("The Phantom of the Opera", "Gaston Leroux"),
("The Sound and the Fury", "William Faulkner"),
("The Wind-Up Bird Chronicle", "Haruki Murakami"),
("Man's Search for Meaning", "Viktor E. Frankl"),
("The Shack", "William Paul Young"),
("Roots: The Saga of an American Family", "Alex Haley"),
("The Night Circus", "Erin Morgenstern"),
("Fear and Loathing in Las Vegas", "Hunter S. Thompson"),
("Blindness", "José Saramago"),
("Island of the Blue Dolphins (Island of the Blue Dolphins, #1)", "Scott O&#39;Dell"),
("Stranger in a Strange Land", "Robert A. Heinlein"),
("The Complete Calvin and Hobbes", "Bill Watterson"),
("Delirium (Delirium, #1)", "Lauren Oliver"),
("For Whom the Bell Tolls", "Ernest Hemingway"),
("I Know This Much Is True", "Wally Lamb"),
("The Selection (The Selection, #1)", "Kiera Cass"),
("Beautiful Disaster (Beautiful, #1)", "Jamie McGuire"),
("The Guernsey Literary and Potato Peel Pie Society", "Mary Ann Shaffer"),
("White Oleander", "Janet Fitch"),
("The House of the Spirits", "Isabel Allende"),
("A Clash of Kings  (A Song of Ice and Fire, #2)", "George R.R. Martin"),
("The Vampire Lestat (The Vampire Chronicles, #2)", "Anne Rice"),
("Lamb: The Gospel According to Biff, Christ's Childhood Pal", "Christopher Moore"),
("The Once and Future King (The Once and Future King #1-4)", "T.H. White"),
("Othello", "William Shakespeare"),
("The Girl Who Kicked the Hornet's Nest (Millennium, #3)", "Stieg Larsson"),
("The Historian", "Elizabeth Kostova"),
("King Lear", "William Shakespeare"),
("Into the Wild", "Jon Krakauer"),
("Flow Down Like Silver: Hypatia of Alexandria", "Ki Longfellow"),
("The Idiot", "Fyodor Dostoyevsky"),
("The Green Mile", "Stephen King"),
("Paper Towns", "John Green"),
("Uncle Tom's Cabin", "Harriet Beecher Stowe"),
("James and the Giant Peach", "Roald Dahl"),
("The Thirteenth Tale", "Diane Setterfield"),
("Speak", "Laurie Halse Anderson"),
("All Creatures Great and Small", "James Herriot"),
("Neverwhere", "Neil Gaiman"),
("Misery", "Stephen King"),
("Leaves of Grass", "Walt Whitman"),
("Invisible Man", "Ralph Ellison"),
("Catching Fire (The Hunger Games, #2)", "Suzanne Collins"),
("Where the Red Fern Grows", "Wilson Rawls"),
("The Cider House Rules", "John Irving"),
("Different Seasons", "Stephen King"),
("Paradise Lost", "John Milton"),
("Graceling (Graceling Realm, #1)", "Kristin Cashore"),
("Inkheart (Inkworld, #1)", "Cornelia Funke"),
("The Complete Works", "William Shakespeare"),
("Candide", "Voltaire"),
("Howl's Moving Castle (Howl's Moving Castle #1)", "Diana Wynne Jones"),
("The Things They Carried", "Tim O&#39;Brien"),
("The Awakening", "Kate Chopin"),
("Walden", "Henry David Thoreau"),
("Sophie's Choice", "William Styron"),
("Heidi", "Johanna Spyri"),
("The Prince of Tides", "Pat Conroy"),
("Are You There God? It's Me, Margaret", "Judy Blume"),
("Throne of Glass (Throne of Glass, #1)", "Sarah J. Maas"),
("Sophie's World", "Jostein Gaarder"),
("Dead Until Dark (Sookie Stackhouse, #1)", "Charlaine Harris"),
("Foundation (Foundation #1)", "Isaac Asimov"),
("The Monster at the End of this Book", "Jon Stone"),
("The Time Machine", "H.G. Wells"),
("City of Lost Souls (The Mortal Instruments, #5)", "Cassandra Clare"),
("Cinder (The Lunar Chronicles, #1)", "Marissa Meyer"),
("Norwegian Wood", "Haruki Murakami"),
("The Complete Sherlock Holmes", "Arthur Conan Doyle"),
("Fifty Shades Darker (Fifty Shades, #2)", "E.L. James"),
("Franny and Zooey", "J.D. Salinger"),
("Fried Green Tomatoes at the Whistle Stop Cafe", "Fannie Flagg"),
("Bridget Jones's Diary (Bridget Jones, #1)", "Helen Fielding"),
("The Power of One (The Power of One, #1)", "Bryce Courtenay"),
("The Secret History", "Donna Tartt"),
("Middlemarch", "George Eliot"),
("The Magician's Nephew (Chronicles of Narnia, #6)", "C.S. Lewis"),
("Things Fall Apart (The African Trilogy, #1)", "Chinua Achebe"),
("The Son of Neptune (The Heroes of Olympus, #2)", "Rick Riordan"),
("Kafka on the Shore", "Haruki Murakami"),
("Bel Canto", "Ann Patchett"),
("Cold Mountain", "Charles Frazier"),
("The Complete Novels", "Jane Austen"),
("A Short History of Nearly Everything", "Bill Bryson"),
("Fifty Shades Freed (Fifty Shades, #3)", "E.L. James"),
("Mrs. Dalloway", "Virginia Woolf"),
("A Time to Kill", "John Grisham"),
("Stardust", "Neil Gaiman"),
("Gulliver's Travels", "Jonathan Swift"),
("The Qur'an / القرآن الكريم", "Anonymous"),
("A Portrait of the Artist as a Young Man", "James Joyce"),
("If I Stay (If I Stay, #1)", "Gayle Forman"),
("Allegiant (Divergent, #3)", "Veronica Roth"),
("The Wise Man's Fear (The Kingkiller Chronicle, #2)", "Patrick Rothfuss"),
("Never Let Me Go", "Kazuo Ishiguro"),
("Beautiful Creatures (Caster Chronicles, #1)", "Kami Garcia"),
("Black Beauty", "Anna Sewell"),
("Number the Stars", "Lois Lowry"),
("Dark Lover (Black Dagger Brotherhood, #1)", "J.R. Ward"),
("The Art of Racing in the Rain", "Garth Stein"),
("Legend (Legend, #1)", "Marie Lu"),
("Eldest (The Inheritance Cycle, #2)", "Christopher Paolini"),
("The Witches", "Roald Dahl"),
("V for Vendetta", "Alan Moore"),
("Love You Forever", "Robert Munsch"),
("The Hound of the Baskervilles (Sherlock Holmes, #5)", "Arthur Conan Doyle"),
("A Separate Peace", "John Knowles"),
("The Gunslinger (The Dark Tower, #1)", "Stephen King"),
("Go Ask Alice", "Beatrice Sparks (as &quot;Anonymous&quot;)"),
("As I Lay Dying", "William Faulkner"),
("Fangirl", "Rainbow Rowell"),
("Mansfield Park", "Jane Austen"),
("The Tell-Tale Heart and Other Writings", "Edgar Allan Poe"),
("Dear John", "Nicholas Sparks"),
("Tuck Everlasting", "Natalie Babbitt"),
("The Mark of Athena (The Heroes of Olympus, #3)", "Rick Riordan"),
("Crescendo (Hush, Hush, #2)", "Becca Fitzpatrick"),
("White Fang", "Jack London"),
("My Ántonia", "Willa Cather"),
("The Amazing Adventures of Kavalier &amp; Clay", "Michael Chabon"),
("Do Androids Dream of Electric Sheep?", "Philip K. Dick"),
("Gone Girl", "Gillian Flynn"),
("Beowulf", "Unknown"),
("The Firm", "Robin A.H. Waterfield"),
("Brisingr  (The Inheritance Cycle, #3)", "Christopher Paolini"),
("The Last Song", "Nicholas Sparks"),
("The Graveyard Book", "Neil Gaiman"),
("The English Patient", "Michael Ondaatje"),
("Midnight's Children", "Salman Rushdie"),
("Obsidian (Lux, #1)", "Jennifer L. Armentrout"),
("Stargirl (Stargirl, #1)", "Jerry Spinelli"),
("Eleanor &amp; Park", "Rainbow Rowell"),
("A Child Called &quot;It&quot; (Dave Pelzer #1)", "Dave Pelzer"),
("Zen and the Art of Motorcycle Maintenance: An Inquiry Into Values", "Robert M. Pirsig"),
("Doctor Zhivago", "Boris Pasternak"),
("Evermore (The Immortals, #1)", "Alyson Noel"),
("Like Water for Chocolate", "Laura Esquivel"),
("Tao Te Ching", "Lao Tzu"),
("The Eye of the World (Wheel of Time, #1)", "Robert Jordan"),
("The Martian Chronicles", "Ray Bradbury"),
("The Amber Spyglass (His Dark Materials, #3)", "Philip Pullman"),
("Breakfast at Tiffany's", "Truman Capote"),
("The Complete Maus (Maus, #1-2)", "Art Spiegelman"),
("Robinson Crusoe", "Daniel Defoe"),
("The Angel Experiment (Maximum Ride, #1)", "James Patterson"),
("Inferno (The Divine Comedy #1)", "Dante Alighieri"),
("Steppenwolf", "Hermann Hesse"),
("The Hunchback of Notre-Dame", "Victor Hugo"),
("'Salem's Lot", "Stephen King"),
("The Diary of a Young Girl", "Anne Frank"),
("The Origin of Species", "Charles Darwin"),
("Dragonfly in Amber (Outlander, #2)", "Diana Gabaldon"),
("The Subtle Knife (His Dark Materials, #2)", "Philip Pullman"),
("A Streetcar Named Desire", "Tennessee Williams"),
("Snow Flower and the Secret Fan", "Lisa See"),
("Cloud Atlas", "David Mitchell"),
("A Fine Balance", "Rohinton Mistry"),
("Shatter Me (Shatter Me, #1)", "Tahereh Mafi"),
("Death of a Salesman", "Arthur Miller"),
("Faust: First Part", "Johann Wolfgang von Goethe"),
("The Scarlet Pimpernel", "Emmuska Orczy"),
("The Shipping News", "Annie Proulx"),
("The BFG", "Roald Dahl"),
("Midnight in the Garden of Good and Evil: A Savannah Story", "John Berendt"),
("Breakfast of Champions", "Kurt Vonnegut"),
("Anna and the French Kiss (Anna and the French Kiss, #1)", "Stephanie Perkins"),
("American Psycho", "Bret Easton Ellis"),
("Mockingjay (The Hunger Games, #3)", "Suzanne Collins"),
("High Fidelity", "Nick Hornby"),
("Houdini Heart", "Ki Longfellow"),
("The Chosen", "Chaim Potok"),
("The Prince", "Niccolò Machiavelli"),
("Room", "Emma Donoghue"),
("Hopeless (Hopeless, #1)", "Colleen Hoover"),
("Matched (Matched, #1)", "Ally Condie"),
("Betrayed (House of Night, #2)", "P.C. Cast"),
("The Reader", "Bernhard Schlink"),
("Nineteen Minutes", "Jodi Picoult"),
("The Plague", "Albert Camus"),
("Daughter of Smoke &amp; Bone (Daughter of Smoke &amp; Bone, #1)", "Laini Taylor"),
("Me Before You (Me Before You, #1)", "Jojo Moyes"),
("Infinite Jest", "David Foster Wallace"),
("The Tales of Beedle the Bard", "J.K. Rowling"),
("The Virgin Suicides", "Jeffrey Eugenides"),
("Untamed (House of Night, #4)", "P.C. Cast"),
("Flowers in the Attic (Dollanganger, #1)", "V.C. Andrews"),
("The Remains of the Day", "Kazuo Ishiguro"),
("Jonathan Strange &amp; Mr Norrell", "Susanna Clarke"),
("Unbroken: A World War II Story of Survival, Resilience, and Redemption",
"Laura Hillenbrand"),
("Lover Awakened (Black Dagger Brotherhood, #3)", "J.R. Ward"),
("The Final Empire (Mistborn, #1)", "Brandon Sanderson"),
("The Age of Innocence", "Edith Wharton"),
("City of Heavenly Fire (The Mortal Instruments, #6)", "Cassandra Clare"),
("Divine Secrets of the Ya-Ya Sisterhood", "Rebecca Wells"),
("Artemis Fowl (Artemis Fowl, #1)", "Eoin Colfer"),
("Blood Meridian, or the Evening Redness in the West", "Cormac McCarthy"),
("Redeeming Love", "Francine Rivers"),
("Chosen (House of Night, #3)", "P.C. Cast"),
("Neuromancer", "William Gibson"),
("The Waste Land", "T.S. Eliot"),
("A Feast for Crows (A Song of Ice and Fire, #4)", "George R.R. Martin"),
("The Pearl", "John Steinbeck"),
("The Way of Kings (The Stormlight Archive, #1)", "Brandon Sanderson"),
("Ready Player One", "Ernest Cline"),
("Me Talk Pretty One Day", "David Sedaris"),
("Northanger Abbey", "Jane Austen"),
("Shantaram", "Gregory David Roberts"),
("The Devil in the White City: Murder, Magic, and Madness at the Fair That),
(Changed America", "Erik Larson"),
("The Twilight Collection (Twilight, #1-3)", "Stephenie Meyer"),
("The Jungle", "Upton Sinclair"),
("Snow Falling on Cedars", "David Guterson"),
("Pippi Longstocking", "Astrid Lindgren"),
("Everything Is Illuminated", "Jonathan Safran Foer"),
("The Voyage of the Dawn Treader (Chronicles of Narnia, #3)", "C.S. Lewis"),
("Waiting for Godot", "Samuel Beckett"),
("To the Lighthouse", "Virginia Woolf"),
("The Lost Symbol (Robert Langdon, #3)", "Dan Brown"),
("Dubliners", "James Joyce"),
("Wonder", "R.J. Palacio"),
("The Strange Case of Dr. Jekyll and Mr. Hyde", "Robert Louis Stevenson"),
("Blood River: A Journey to Africa's Broken Heart", "Tim Butcher"),
("The Last Battle (Chronicles of Narnia, #7)", "C.S. Lewis"),
("A Room with a View", "E.M. Forster"),
("Torment (Fallen, #2)", "Lauren Kate"),
("I, Claudius (Claudius, #1)", "Robert Graves"),
("The Iron King (The Iron Fey, #1)", "Julie Kagawa"),
("Bloodlines (Bloodlines, #1)", "Richelle Mead"),
("I, Robot (Robot #0.1)", "Isaac Asimov"),
("Three Cups of Tea: One Man's Mission to Promote Peace ... One School at a),
(Time", "Greg Mortenson"),
("The Mortal Instruments Boxed Set: City of Bones; City of Ashes; City of Glass),
((The Mortal Instruments, #1-3)", "Cassandra Clare"),
("Brideshead Revisited", "Evelyn Waugh"),
("Johnny Got His Gun", "Dalton Trumbo"),
("Bleak House", "Charles Dickens"),
("Miss Peregrine’s Home for Peculiar Children (Miss Peregrine’s Peculiar),
(Children, #1)", "Ransom Riggs"),
("Vanity Fair", "William Makepeace Thackeray"),
("Carrie", "Stephen King"),
("Bared to You (Crossfire, #1)", "Sylvia Day"),
("11/22/63", "Stephen King"),
("The Witching Hour (Lives of the Mayfair Witches, #1)", "Anne Rice"),
("Halfway to the Grave (Night Huntress, #1)", "Jeaniene Frost"),
("A Dance with Dragons (A Song of Ice and Fire, #5)", "George R.R. Martin"),
("The God Delusion", "Richard Dawkins"),
("I Know Why the Caged Bird Sings", "Maya Angelou"),
("Voyager (Outlander, #3)", "Diana Gabaldon"),
("Harry Potter Boxset (Harry Potter, #1-7)", "J.K. Rowling"),
("The Exorcist", "William Peter Blatty"),
("Chocolat (Chocolat, #1)", "Joanne Harris"),
("A Great and Terrible Beauty (Gemma Doyle, #1)", "Libba Bray"),
("The Complete Poems", "Emily Dickinson"),
("The House of Hades (The Heroes of Olympus, #4)", "Rick Riordan"),
("Perfect Chemistry (Perfect Chemistry, #1)", "Simone Elkeles"),
("The Republic", "Plato"),
("Of Human Bondage", "W. Somerset Maugham"),
("Wizard's First Rule (Sword of Truth, #1)", "Terry Goodkind"),
("Are You My Mother?", "P.D. Eastman"),
("The Summoning (Darkest Powers, #1)", "Kelley Armstrong"),
("Cannery Row", "John Steinbeck"),
("North and South", "Elizabeth Gaskell"),
("Snow Crash", "Neal Stephenson"),
("You Are Special (Wemmicksville, #1)", "Max Lucado"),
("Cry, the Beloved Country", "Alan Paton"),
("World War Z: An Oral History of the Zombie War", "Max Brooks"),
("Just Listen", "Sarah Dessen"),
("The One (The Selection, #3)", "Kiera Cass"),
("The Lord of the Rings (The Lord of the Rings, #1-3)", "J.R.R. Tolkien"),
("The 5th Wave (The 5th Wave, #1)", "Rick Yancey"),
("Dead to the World (Sookie Stackhouse, #4)", "Charlaine Harris"),
("The Truth About Forever", "Sarah Dessen"),
("The Unbecoming of Mara Dyer (Mara Dyer, #1)", "Michelle Hodkin"),
("Acheron (Dark-Hunter #14)", "Sherrilyn Kenyon"),
("Lady Chatterley's Lover", "D.H. Lawrence"),
("Hunted (House of Night, #5)", "P.C. Cast"),
("Ishmael: An Adventure of the Mind and Spirit", "Daniel Quinn"),
("Unwind (Unwind, #1)", "Neal Shusterman"),
("Silence (Hush, Hush, #3)", "Becca Fitzpatrick"),
("Nine Stories", "J.D. Salinger"),
("The Glass Menagerie", "Tennessee Williams"),
("The Woman in White", "Wilkie Collins"),
("East of Eden", "John Steinbeck"),
("The Polar Express", "Chris Van Allsburg"),
("I Am Number Four (Lorien Legacies, #1)", "Pittacus Lore"),
("The War of the Worlds", "H.G. Wells"),
("Much Ado About Nothing", "William Shakespeare"),
("The Bronze Horseman (The Bronze Horseman, #1)", "Paullina Simons"),
("Wicked Lovely (Wicked Lovely, #1)", "Melissa Marr"),
("The Hours", "Michael Cunningham"),
("The Last Lecture", "Randy Pausch"),
("The Bean Trees (Greer Family, #1)", "Barbara Kingsolver"),
("Being and Time", "Martin Heidegger"),
("Twelfth Night", "William Shakespeare"),
("I Capture the Castle", "Dodie Smith"),
("The Arabian Nights", "Anonymous"),
("A Discovery of Witches (All Souls Trilogy, #1)", "Deborah Harkness"),
("Demian. Die Geschichte von Emil Sinclairs Jugend", "Hermann Hesse"),
("Sarah's Key", "Tatiana de Rosnay"),
("Swann's Way (In Search of Lost Time, #1)", "Marcel Proust"),
("Cyrano de Bergerac", "Edmond Rostand"),
("Into Thin Air: A Personal Account of the Mount Everest Disaster", "Jon Krakauer"),
("The Martian", "Andy Weir"),
("The Host (The Host, #1)", "Stephenie Meyer"),
("Interpreter of Maladies", "Jhumpa Lahiri"),
("Coraline", "Neil Gaiman"),
("The Horse and His Boy (Chronicles of Narnia, #5)", "C.S. Lewis"),
("Crown of Midnight (Throne of Glass, #2)", "Sarah J. Maas"),
("P.S. I Love You", "Cecelia Ahern"),
("Slammed (Slammed, #1)", "Colleen Hoover"),
("All the King's Men", "Robert Penn Warren"),
("The Goose Girl (The Books of Bayern, #1)", "Shannon Hale"),
("Angelfall (Penryn &amp; the End of Days, #1)", "Susan Ee"),
("Sabriel (Abhorsen,  #1)", "Garth Nix"),
("World Without End (The Pillars of the Earth, #2)", "Ken Follett"),
("Peace Like a River", "Leif Enger"),
("Far from the Madding Crowd", "Thomas Hardy"),
("Lover Eternal (Black Dagger Brotherhood, #2)", "J.R. Ward"),
("Julius Caesar", "William Shakespeare"),
("The Merchant of Venice", "William Shakespeare"),
("The Red Pyramid (Kane Chronicles, #1)", "Rick Riordan"),
("The Elite (The Selection, #2)", "Kiera Cass"),
("Before I Fall", "Lauren Oliver"),
("Pet Sematary", "Stephen King"),
("2001: A Space Odyssey (Space Odyssey, #1)", "Arthur C. Clarke"),
("Mythology: Timeless Tales of Gods and Heroes", "Edith Hamilton"),
("Little House in the Big Woods (Little House, #1)", "Laura Ingalls Wilder"),
("Speaker for the Dead (Ender's Saga, #2)", "Orson Scott Card"),
("Little House on the Prairie (Little House, #2)", "Laura Ingalls Wilder"),
("Gone (Gone, #1)", "Michael  Grant");
